### ISSUE TITLE
KSY File

### ISSUE THREAD

**Issue by senormeow** [sonusz/PhasorToolBox#1]
Do you have the .ksy file used in the Parser?

**Comment by sonusz** [comment]
I have the .ksy file, but not in the Parser right now. I can add another branch to put the .ksy file.
Please note that, the parse of PMU measurement packet requires the configuration packet. My solution is to assume that the program needs to attach the configuration packet in front of each measurement packet before sending it to the parser.

**Comment by sonusz** [comment]
I have uploaded the kaitai folder under the master branch.
